# Generated by Django 4.1.3 on 2022-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('carImage', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='uploadVIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('vinImage', models.ImageField(upload_to='imgVIN/')),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
