# Generated by Django 4.1.3 on 2022-11-22 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.current_user


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_uploadcar_uploadvin_alter_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcar',
            name='uname',
            field=models.ForeignKey(default=webapp.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadvin',
            name='uname',
            field=models.ForeignKey(default=webapp.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
